iarahealth/adapters

- src/syncfusion/formatter.ts
- src/syncfusion/index.ts
Este PR trata capitalização e a adição de espaços antes ou depois da inferência no momento da inserção no editor de texto.
> feat: handle trailing spaces and capitalization

- src/editor/index.ts
- src/syncfusion/index.ts
Resolve PRT-1761
PR - Salvamento automático do laudo
> Feat: PRT-1761 - Salvamento Automático do laudo no adapters

- src/editor/index.ts
- src/syncfusion/formatter.ts
- src/syncfusion/index.ts
- src/tinymce/index.ts
Iara comands copy and finalize
> Feat/prt 1774 - Iara comands copy and finalize

- src/editor/index.ts
- src/syncfusion/index.ts
- src/tinymce/index.ts
formatter commands: bold, italic, underline and uppercase.
> Feat/prt 1773 - formatter commands

- src/editor/index.ts
- src/tinymce/index.ts
implement get content at editor
> Fix/get content - implement get content at editor

- src/syncfusion/index.ts
Correct get html content from editor by Sfdt.
> feat: get html content from editor correction

- src/syncfusion/index.ts
Add method onDestroy to finish the report in the adapter. Resolve PRT-1806
> feat: add onDestroy

- src/syncfusion/index.ts
Added check for templates to use insertTemplates. Resolve feature/PRT-1771.
> feat: add verify to templates

- src/syncfusion/content.ts
Este PR permite recuperar o conteúdo do editor no formato RTF. Resolve IARA-607.
> feat: get editor RTF content

- src/syncfusion/index.ts
Remove enableLocalPaste. Resolve IARA-617.
> feat: remove enableLocalPaste

- src/editor/index.ts
- src/syncfusion/index.ts
Improve logic to debounce save the report. Resolve PRT-1761
> feat: improve debounce logic to save

- package.json
- src/syncfusion/toolbar/config.ts
- src/syncfusion/toolbar/index.ts
add a custom toolbar itens a locale edition. Resolve PRT-1823.
> feat: add a custom toolbar locale

- src/syncfusion/index.ts
Is template remove div if is phrase dont remove. Remove PRT-1826
> feat: verify is Template

- src/syncfusion/index.ts
Removed unnecessary <\/div><div> when using the paragraph. Resolve PRT-1826
> fix: remove close tag error

- src/editor/index.ts
- src/syncfusion/index.ts
Add logic to save when editor was created. Resolve PRT-1761
> feat: add logic to save when editor created

- src/syncfusion/toolbar/index.ts
Bug where the screen was enlarged when the font was changed. Resolve PRT-1869
> fix: pass logic to method and adjust the height

- src/syncfusion/toolbar/config.ts
- src/syncfusion/toolbar/ribbonTabs.ts
Add font  style status bold, italic, Underline and Strikethrough
> feat: add font style status

- src/syncfusion/toolbar/config.ts
- src/syncfusion/toolbar/index.ts
- src/syncfusion/toolbar/ribbonTabs.ts
Add classic mode to ribbon. Resolve PRT-1853.
> feat: add classic mode to ribbon

- src/syncfusion/toolbar/config.ts
Add popup to insert number of columns and rows. Resolve PRT-1898.
> feat: add popup to insert number of columns

- src/syncfusion/toolbar/index.ts
- src/syncfusion/toolbar/ribbonTabs.ts
Add translate and heitgh of menu ribbon. Resolve PRT-1853
> feat: add translate and heitgh of menu ribbon

- src/syncfusion/navigationFields.ts
- src/syncfusion/toolbar/config.ts
- src/syncfusion/toolbar/ribbonTabs.ts
Add navigation fields in syncfusion. Resolve PRT-1907
> feat: add navigation fields

- src/syncfusion/navigationFields.ts
Added title to navigation field. Resolve PRT-1861
> feat: add title to navigation field

- src/syncfusion/navigationFields/index.ts
- src/syncfusion/toolbar/ribbonTabs.ts
Add mandatory field. Resolve PRT-1760
> feat: add mandatory field

- src/syncfusion/navigationFields/index.ts
- src/syncfusion/toolbar/ribbonTabs.ts
Add optional fields. Resolve PRT-1863.
> feat: add optional fields

- src/syncfusion/index.ts
- src/syncfusion/navigationFields/index.ts
Change colors to bookmarks in navigations fields. Resolve PRT-1952.
> feat: change colors bookmarks

- src/editor/index.ts
- src/editor/navigationFields.ts
- src/syncfusion/navigationFields/index.ts
- src/tinymce/index.ts
- src/tinymce/navigationFields.ts
Has empty required fields. Resolve PRT-1759.
> feat: add has empty required fields

- src/syncfusion/navigationFields/index.ts
- src/syncfusion/toolbar/ribbonTabs.ts
To small screen use the same id to get Navigation fields. Resolve PRT-1970.
> feat: improve navigation fields id

- src/syncfusion/contextMenu/index.ts
- src/syncfusion/navigationFields/index.ts
- src/syncfusion/toolbar/ribbonTabs.ts
Improve navigation by fields. Resolve PRT-1973.
> feat: improve navigation by fields

- src/syncfusion/navigationFields/index.ts
Remove white space when bookmark deleted. Resolve PRT-1984
> feat: remove space

- src/editor/formatter.ts
Remove the function that prevents space separation. Just commented to use in other time. Resolve PRT-1937.
> feat: remove the function that prevents space separation

- src/syncfusion/navigationFields/index.ts
remove white space in goToField. Resolve PRT-1986
> feat: remove white space in goToField

- src/syncfusion/navigationFields/index.ts
Clean the content in selection to add a bookmark with content. Resolve PRT-1989.
> feat: improve logic to add a new bookmark

- src/editor/index.ts
- src/syncfusion/index.ts
no save empty content. Resolve PRT-1998.
> feat: remove content empty

- src/syncfusion/index.ts
Remove space when set a template. Resolve PRT-2007
> fix: space add when set a template

- package-lock.json
- package.json
- src/syncfusion/bookmarks/index.ts
- src/syncfusion/index.ts
Create inference fields. Resolve PRT-2027.
> feat: add inference fields

- src/syncfusion/contextMenu/index.ts
- src/syncfusion/navigationFields/index.ts
- src/syncfusion/toolbar/config.ts
Improve insertField. Resolve PRT-2029.
> feat: improve insertField

- src/syncfusion/index.ts
Add next field method when insert a template. Resolve PRT-2036
> feat: add next field when insert a template

- src/editor/index.ts
- src/syncfusion/bookmarks/index.ts
Added highlightInference to check what is being added by inference. Resolve PRT-2044
> feat: improve logic to get highlightInference by configs

- package-lock.json
- package.json
- src/syncfusion/navigationFields/additiveFieldModal.ts
- src/syncfusion/navigationFields/bookmark.ts
Allow you to re-edit fields in the additive field record. Resolve PRT-2039
> feat: reorder list

- src/syncfusion/index.ts
Improve logic to know the richText is a template or phrase. Resolve PRT-1935
> fix: to identificate a phrase in inference

- src/syncfusion/navigationFields/index.ts
Previous navigation skip field. PRT-2005
> fix: previous navigation skip field

- src/syncfusion/navigationFields/index.ts
Verify navigationBookmark is undefined. Resolve PRT-2107
> fix: verify is navigationBookmark undefined

- src/syncfusion/navigationFields/index.ts
Improve logic to remove space. Resolve PRT-2108
> fix: improve logic to remove space

- src/syncfusion/index.ts
- src/syncfusion/selection.ts
Fix: cursor move position in inference isFinal. Resolve PRT-2140
> fix: cursor move position in finish recognition

- src/syncfusion/content/write.ts
Fix no navigation to first bookmark. Resolve PRT-2217
> fix: navigation to first bookmark

- src/syncfusion/index.ts
Template be entered for the function to run. Resolve PRT-2218
> fix: template be entered for the function to run

- src/syncfusion/language/iaraLanguages.ts
- src/syncfusion/language/language.ts
- src/syncfusion/navigationFields/index.ts
Add translate to custom fields title and content. Resolve PRT-2243
> fix: translate custom fields

- src/syncfusion/shortcuts/index.ts
Remove / shortcut to open assistant. Resolve PRT-2260
> feat: removed / shortcut to open assistant

- src/syncfusion/assistant/assistant.ts
Add accept all revisions changes in changes generated by IA. Resolve PRT-2264
> feat: add acceptAll changes

- src/syncfusion/content/write.ts
Add verification to line break dont clear on delete selection. Resolve PRT-2228
> feat: add verification to line break dont clear on delete selection

- src/syncfusion/toolbar/tabs.ts
Feat: remove additive button. Resolve PRT-2245
> feat: remove additive button

- src/syncfusion/content/read.ts
- src/syncfusion/index.ts
- src/syncfusion/navigationFields/index.ts
Improve debounce logic to get current content in the editor to copy area. Resolve PRT-2277
> fix: no update content value when copy a text

- src/syncfusion/content/write.ts
Fixed added space when overwriting a navigation bookmark. Resolve PRT-2280
> fix: space added when a bookmark selected

- src/syncfusion/assistant/assistant.ts
I added a bookmark to the assistant. I created a function to generate bookmarks and highlight selections to see what is new in a generation. Resolve PRT-2293
> feat: add bookmark in assistant generate report

- src/editor/index.ts
- src/syncfusion/navigationFields/additive.ts/dialog.ts
- src/syncfusion/navigationFields/additive.ts/list.ts
- src/syncfusion/navigationFields/index.ts
- src/syncfusion/toolbar/tabs.ts
When is a registry mode the additive opens the form, when is in use mode shows the list of fields. Resolve PRT-2224
> feat: add addittive navigationMode

- src/editor/locales.ts
- src/syncfusion/assistant/assistant.ts
- src/syncfusion/index.ts
Add the command "iara" to open the AI assistant. Resolve PRT-2316
> feat: add iara command to open assistant

- src/syncfusion/assistant/assistant.ts
- src/syncfusion/config.ts
- src/syncfusion/index.ts
Add user_rules configs to the AI assistant to get user settings. Resolve PRT-2315
> feat: add user_rules config and get lib dispatcher

- src/syncfusion/config.ts
- src/syncfusion/index.ts
feat add config draggable in assistant. Resolve PRT-2311
> feat: add config draggable in assistant

- src/syncfusion/config.ts
Remove the need to pass group_rules
> fix: remove the need to pass group_rules

- src/syncfusion/assistant/assistant.ts
Fix: update the config in the dispatcher to get the correct value. Resolve PRT-2348
> fix: to update config assistant

- src/syncfusion/assistant/assistant.ts
Get the value to set the impression in the report. Resolve PRT-2350
> feat: pass new value to insert impression

- src/syncfusion/assistant/assistant.ts
Adjusted the loop in the _ensureParagraphsForDiagnosticInsertion logic. Resolve PRT-2358
> fix: the loop logic and improve the _ensureParagraphsForDiagnosticInsertion

- src/syncfusion/index.ts
Improve the command iara to open the assistant when the regex is respected. Resolve PRT-2374
> fix: iara command to open assistant

- src/syncfusion/content/read.ts
- src/syncfusion/content/write.ts
Add preferred font based on the config. Resolve AD-5
> feat: add style in html when html dont have style

- src/syncfusion/content/read.ts
Add paragraphSpacing when we don't have styles in HTML. Resolve AD-9
> feat: add paragraphSpacing when no have styles

- src/editor/index.ts
- src/syncfusion/index.ts
Add _currentAssistantGeneratedReportHistory and add metadata on _updateReport.
Resolve PRT-2387
> feat: Add _currentAssistantGeneratedReportHistory and metadata
